# -*- coding: utf-8 -*-
"""nicholas_trabalho1.ipnyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xQpMFPK-q9fw1aZrULMgJgTHzbYXB_uu
"""

import pandas as pd
import numpy as  np

"""DataFrame Pandas"""

arquivo = pd.read_excel("/content/dados_abertos.xlsx")

arquivo

arquivo.describe()

"""Base ordenada do campo titulo"""

arquivo["Titulo"]

"""Dados filtrados"""

arquivo[arquivo['Setor']== 'Tecnologia']